[tool.poetry]
name = "logstead-backend"
version = "0.1.0"
description = "Logstead FastAPI backend"
authors = ["Your Name <you@example.com>"]

# Add packages section for Poetry
packages = [
	{ include = "services" },
	{ include = "main.py" }
]

[tool.poetry.dependencies]
python = ">=3.13"
fastapi = "*"
uvicorn = {extras = ["standard"], version = "*"}


[tool.poetry.dev-dependencies]
flake8 = "*"
pytest = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
